### PR TITLE
Do not extend Process class on iOS

### PR DESCRIPTION
**Pull request by patrykwas**
I want to use Fluent on the iOS, but extending Process class in vapor/core prevents compilation for iOS devices.

### CODE REVIEW

**Comment by twof** [comment]
See: https://github.com/vapor/fluent-sqlite/issues/7

Are you planning on using Fluent with something other than Sqlite?

**Comment by 0xTim** [comment]
I would LOVE a Core data Fluent wrapper....

**Comment by patrykwas** [comment]
@twof  Thanks for the link
I was planning to use sqlite but from your link I understand that it's not that simple

**Review by tanner0101 — APPROVED** [review]
Thanks!

**Comment by tanner0101** [comment]
Agreed, core data wrapper for Fluent would be epic. Hopefully this gets us one step closer 👍

**Comment by penny-coin** [comment]
Hey @patrykwas, you just merged a pull request, have a coin! 

You now have 1 coins.

**Pull request merged**
