### PR TITLE
Added quotation marks to the serialized header values

### PR DESCRIPTION
**Pull request by Cellane**
… at least I hope so 😅 

This tiny PR is hopefully a fix to vapor/multipart#22 and to two days of banging my head against a wall.

### CODE REVIEW

**Comment by Cellane** [comment]
It seems that if we decide to go for this, some tests will have to be updated. I’m not 100% sure if I’m reading the build log correctly but it’s possible that only [this test](https://github.com/vapor/vapor/blob/master/Tests/VaporTests/ApplicationTests.swift#L199-L222) is failing? If so, I can prepare another PR for that in the vapor/vapor repository.

**Review by tanner0101 — COMMENTED** [review]
Code LGTM. 🙌  I omitted the quotes originally to save a couple of bytes but looks like we need 'em. Gotta love the web haha. As you mentioned, we will also need to fix the test here: https://github.com/vapor/vapor/blob/master/Tests/VaporTests/ApplicationTests.swift#L199-L222

We be great if we could get a PR up for that before merging this so that Vapor's tests aren't broken.

**Comment by tanner0101** [comment]
BTW, you can change which branch of Vapor is checked out during tests here: https://github.com/vapor/core/blob/master/circle.yml#L40

We should change this to the branch of Vapor that you apply the fix to, that way we can get green checks here before merging.

I've invited you to the contributors team so you should be able to create local branches now. 👍

**Comment by Cellane** [comment]
Aah, that’s how you do that! Okay, will submit PR for the tests by creating new branch directly on vapor/vapor instead of Cellane/vapor, then change `circle.yml` on this PR.

Can the changed `circle.yml` then be excluded from the final merge though? Apologies, this is the first time contributing in this cross-repository fashion.

**Comment by tanner0101** [comment]
@Cellane once the merge goes through I just change it on master manually. Small price to pay for making sure everything is works haha.

**Review by tanner0101 — APPROVED** [review]

**Comment by tanner0101** [comment]
Thanks!

**Comment by penny-coin** [comment]
Hey @Cellane, you just merged a pull request, have a coin! 

You now have 68 coins.

**Pull request merged**
