### PR TITLE
Bits integrate

### PR DESCRIPTION
**Pull request by loganwright**

### CODE REVIEW

**Comment by tanner0101** [comment]
If master starts breaking API we will need to make sure to apply bug fixes to the last 1.x.x tag. That sounds like it might be easier than trying to manage a 2.0 branch.

**Comment by loganwright** [comment]
@tannernelson I was under the impression that with very minimal changes, we'd basically be calling older versions unsupported. This was discussed the other day regarding semver changes internally and our ability to more quickly say old versions aren't supported. Either way, cutting a final 1.+ branch for bug fixes wouldn't be too tricky as long as we're not supporting 4 or 5 different versions and mostly saying you have to stay with us until major releases.

**Comment by tanner0101** [comment]
@LoganWright I meant how to fix bugs that arise as we're developing 2.0. I agree with what you're saying there about supporting older major versions.

**Comment by loganwright** [comment]
@tannernelson ahh, I'm with you now 👍 

I think definitely any bugs we find should be added to the 1.0 tag while we're developing 2.0. Hopefully won't be too tricky, but we'll probably hit a couple of snags.

**Pull request merged**
